# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
        "ccm"
        "ctr"
        "iwlmvm"
        "iwlwifi"
      ];
      kernelModules = [
        "dm-snapshot"
        "cryptd"
      ];

      systemd = {
        enable = true;

        packages = [ pkgs.wpa_supplicant ];
        initrdBin = [ pkgs.wpa_supplicant ];

        targets.initrd.wants = [ "wpa_supplicant@wlp6s0.service" ];
        services."wpa_supplicant@".unitConfig.DefaultDependencies = false;

        network = {
          enable = true;
          networks = {
            "10-wlan" = {
              matchConfig.Name = "wlp6s0";
              networkConfig.DHCP = "yes";
            };
          };
        };

        users.root.shell = "/bin/systemd-tty-ask-password-agent";
      };

      # Generated with wpa_passphrase <ssid> "<password>" > wpa_supplicant.conf
      secrets."/etc/wpa_supplicant/wpa_supplicant-wlp6s0.conf" = /root/secret/wpa_supplicant.conf;

      network = {
        enable = true;
        ssh = {
          enable = true;
          port = 22;
          hostKeys = [ "/etc/ssh/ssh_host_ed25519_key" ];
          authorizedKeys = [
            "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOW8JjnxKQsDA/y88lkCr6/Z0nxp4/veNdZ0f/hB9qHR"
          ];
        };
      };

      luks.devices."cryptroot".device = "/dev/disk/by-label/encrypted";
    };

    kernelModules = [ "kvm-amd" ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-label/boot";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
  };

  swapDevices = [
    {
      device = "/dev/disk/by-label/swap";
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
