"""Compose a Database and a Backup for an AppEnvironment.

This is a reference example showing all the key patterns for a Python
composition function. It composes two resources with a dependency gate
(Backup waits for Database to be ready), uses Pydantic models where
available, raw dicts where not, tracks readiness, emits structured
events, and protects deletion ordering with a Usage.
"""

from crossplane.function import resource, response
from crossplane.function.proto.v1 import run_function_pb2 as fnv1

# Pydantic models generated by `up project build` from XRDs and provider CRDs.
from .model.ai.example.appenvironment import v1alpha1
from .model.io.upbound.m.aws.rds.instance import v1beta1 as rdsv1beta1
from .model.io.k8s.apimachinery.pkg.apis.meta import v1 as metav1


def _has_condition(req: fnv1.RunFunctionRequest, name: str, cond: str) -> bool:
    """Check if an observed composed resource has a condition set to True.

    Uses the SDK's resource.get_condition which reads status.conditions from
    the protobuf Struct representation of the resource.
    """
    observed = req.observed.resources.get(name)
    if observed is None:
        return False
    return resource.get_condition(observed.resource, cond).status == "True"


def compose(req: fnv1.RunFunctionRequest, rsp: fnv1.RunFunctionResponse):
    """Compose a Database and Backup for the AppEnvironment XR."""

    # Deserialize the XR into a Pydantic model for typed field access.
    xr = v1alpha1.AppEnvironment(
        **resource.struct_to_dict(req.observed.composite.resource)
    )

    # Validate the spec. Warnings are for user-actionable errors that
    # won't self-resolve.
    if not xr.spec.region:
        response.warning(rsp, "spec.region is required")
        return

    # Protobuf Struct delivers all numbers as float — cast explicitly.
    storage_gb = int(xr.spec.storageGb or 20)

    # Always compose the Database using Pydantic models.
    resource.update(
        rsp.desired.resources["database"],
        rdsv1beta1.Instance(
            spec=rdsv1beta1.Spec(
                forProvider=rdsv1beta1.ForProvider(
                    region=xr.spec.region,
                    instanceClass="db.t3.micro",
                    allocatedStorage=storage_gb,
                    engine="postgres",
                ),
            ),
        ),
    )

    # Gate the Backup on the Database being Ready. But once composed,
    # always keep emitting it — omitting a resource from desired state
    # tells Crossplane to delete it.
    db_ready = _has_condition(req, "database", "Ready")
    backup_exists = "backup" in req.observed.resources

    if db_ready or backup_exists:
        # Raw dicts for resources without generated Pydantic models
        # (e.g. third-party CRDs not in the project's dependencies).
        resource.update(rsp.desired.resources["backup"], {
            "apiVersion": "backup.aws.upbound.io/v1beta1",
            "kind": "Plan",
            "spec": {
                "forProvider": {
                    "region": xr.spec.region,
                    "name": f"{xr.metadata.name}-backup",
                },
            },
        })

    # Protect the Database from deletion until the Backup is gone.
    # Without this, both delete simultaneously and the Backup can't
    # clean up its snapshots.
    if db_ready or backup_exists:
        resource.update(rsp.desired.resources["usage-db-by-backup"], {
            "apiVersion": "protection.crossplane.io/v1beta1",
            "kind": "Usage",
            "spec": {
                "of": {
                    "apiVersion": "rds.aws.m.upbound.io/v1beta1",
                    "kind": "Instance",
                    "resourceSelector": {"matchControllerRef": True},
                },
                "by": {
                    "apiVersion": "backup.aws.upbound.io/v1beta1",
                    "kind": "Plan",
                    "resourceSelector": {"matchControllerRef": True},
                },
                "replayDeletion": True,
            },
        })
        rsp.desired.resources["usage-db-by-backup"].ready = fnv1.READY_TRUE

    # Write status for consumers of this XR.
    status: dict = {"region": xr.spec.region}
    db_observed = req.observed.resources.get("database")
    if db_observed:
        db_dict = resource.struct_to_dict(db_observed.resource)
        endpoint = db_dict.get("status", {}).get("atProvider", {}).get("endpoint")
        if endpoint:
            status["endpoint"] = endpoint
    resource.update(rsp.desired.composite, {"status": status})

    # Track readiness. Emit Normal events for time-bounded waiting and
    # one-time transitions. Never emit Normal in the steady state.
    not_ready = []

    if db_ready:
        rsp.desired.resources["database"].ready = fnv1.READY_TRUE
        # Transition event: Database just became ready (Backup not yet seen).
        if not backup_exists:
            response.normal(rsp, "Database ready, composing Backup")
    else:
        not_ready.append("database")

    if "backup" in rsp.desired.resources:
        if _has_condition(req, "backup", "Ready"):
            rsp.desired.resources["backup"].ready = fnv1.READY_TRUE
        else:
            not_ready.append("backup")

    # Check if this is a transition to ready.
    was_ready = resource.get_condition(
        req.observed.composite.resource, "Ready"
    ).status == "True"

    if not not_ready:
        rsp.desired.composite.ready = fnv1.READY_TRUE
        if not was_ready:
            response.normal(rsp, f"Ready, endpoint: {status.get('endpoint', 'pending')}")
    else:
        # Normal (not Warning) because this is expected and time-bounded.
        response.normal(rsp, f"Waiting for: {', '.join(not_ready)}")
